import bug from "./bug.png"
import dark from "./dark.png"
import dragon from "./dragon.png"
import electric from "./electric.png"
import fairy from "./fairy.png"
import fighting from "./fighting.png"
import fire from "./fire.png"
import flying from "./flying.png"
import ghost from "./ghost.png"
import grass from "./grass.png"
import ground from "./ground.png"
import ice from "./ice.png"
import poison from "./poison.png"
import steel from "./steel.png"
import rock from "./stone.png"
import water from "./water.png"
import psychic from "./water.png"
import normal from "./normal.png"

// eslint-disable-next-line
export default { normal,bug, dark, dragon, electric, fairy, fighting, fire, flying, ghost, grass, ground, ice, poison, steel, rock, water, psychic }